In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv("car driving risk analysis.csv")

In [3]:
df.head()

speed  risk
0    200    95
1     90    20
2    300    98
3    110    60
4    240    72

In [4]:
df

speed  risk
0     200    95
1      90    20
2     300    98
3     110    60
4     240    72
5     115    10
6      50     7
7     230    85
8     190    45
9     260    91
10    290    82
11    185    59
12    310    93
13     95    18
14     30     2

In [5]:
df.shape

(15, 2)

In [6]:
df.isnull().any()

speed    False
risk     False
dtype: bool

In [7]:
df.isnull().sum()

speed    0
risk     0
dtype: int64

In [9]:
x = df[['speed']]
y = df['risk']

In [10]:
x

speed
0     200
1      90
2     300
3     110
4     240
5     115
6      50
7     230
8     190
9     260
10    290
11    185
12    310
13     95
14     30

In [12]:
y

0     95
1     20
2     98
3     60
4     72
5     10
6      7
7     85
8     45
9     91
10    82
11    59
12    93
13    18
14     2
Name: risk, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.40, random_state = 1)

In [15]:
xtrain

speed
1      90
13     95
0     200
14     30
9     260
8     190
12    310
11    185
5     115

In [16]:
ytrain

1     20
13    18
0     95
14     2
9     91
8     45
12    93
11    59
5     10
Name: risk, dtype: int64

In [17]:
xtest

speed
3     110
7     230
6      50
2     300
10    290
4     240

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
reg = LinearRegression()

In [20]:
reg.fit(xtrain, ytrain)

LinearRegression()

In [21]:
reg.predict(xtest)

array([ 27.15301215,  73.82259334,   3.81822156, 101.04651569,
        97.15738393,  77.7117251 ])

In [23]:
reg.predict([[278]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92.49042581])

In [24]:
reg.predict([[290]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([97.15738393])